# .air.toml

root = "."
tmp_dir = ".air"

[build]
  bin = ".air/main"
  cmd = "go build -o .air/main cmd/main.go"
  delay = 200
  watch_dir = "./"
  include_ext = ["go"]
  exclude_dir = [".air"]
  kill_delay = "0s"
  log = "build-errors.log"
  rerun_delay = 500

[server]
  port = 8080
  full_reload = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true